version: '3.9'
services:
  db:
      container_name: ${PROJECT_NAME}_db
      image: ${DB_TYPE}:${DB_VERSION}
      restart: unless-stopped
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
      ports:
        - ${DB_LOCAL_PORT}:3306
      volumes:
        - ./services/db/my.cnf:/etc/mysql/my.cnf
        - ./services/db/${DB_TYPE}/dump:/var/lib/mysql
        - ./logs/mysql:/var/log/mysql
        - ./data:/docker-entrypoint-initdb.d
  #PHP Container
  phpcnt:
    container_name: ${PROJECT_NAME}_php81
    build:
      context: ./services/php81
    image: ${PROJECT_NAME}_php_81
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./www/:/var/www/
      - ./services/php81/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
  #NGINX Service
  nginxcnt:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}_nginxcnt
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www/:/var/www
      - ./services/nginx/conf.d/:/etc/nginx/conf.d/
      - ./logs/nginx/:/var/log/nginx/
    depends_on:
      - phpcnt
    links:
      - phpcnt
