version: '3.9'
services:
  db:
      container_name: ${PROJECT_NAME}_db
      platform: linux/x86_64
      image: library/${DB_TYPE}:${DB_VERSION}
      restart: unless-stopped
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
      ports:
        - ${DB_LOCAL_PORT}:3306
      volumes:
        - ./services/db/my.cnf:/etc/mysql/my.cnf
        - ./services/db/${DB_TYPE}/dump:/var/lib/mysql
        - ./logs/mysql:/var/log/mysql
        - ./data:/docker-entrypoint-initdb.d
      networks:
        - main_network
  #PHP Container
  phpcnt:
    build:
      args:
        uname: ${PHP_UNAME}
        uid: ${PHP_UID}
        gid: ${PHP_GID}
      context: ./services/php${PHP_VERSION}
    container_name: ${PROJECT_NAME}_php_${PHP_VERSION}
    image: ${PROJECT_NAME}_php_${PHP_VERSION}
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./www/:/var/www/
      - ./services/php${PHP_VERSION}/php.ini:/usr/local/etc/php/php.ini
      - ./logs/xdebug/:/var/log/xdebug/
    depends_on:
      - db
    networks:
        - main_network
  #NGINX Service
  nginxcnt:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}_nginxcnt
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www/:/var/www
      - ./services/nginx/conf.d/:/etc/nginx/conf.d/
      - ./logs/nginx/:/var/log/nginx/
    depends_on:
      - phpcnt
    links:
      - phpcnt
    networks:
      - main_network
  pmacnt:
      build:
        context: ./services/phpmyadmin
      container_name: ${PROJECT_NAME}_pma
      image: ${PROJECT_NAME}_pma
      restart: unless-stopped
      volumes:
          - /sessions
      environment:
        - PMA_HOST=db
        - PMA_PORT=3306
        - PMA_USER=root
        - PMA_PASSWORD=${DB_ROOT_PASSWORD}
        - PMA_ARBITRARY=1
      ports:
        - ${PMA_LOCAL_PORT}:80
      depends_on:
        - db
      networks:
        - main_network
networks:
  main_network:
    driver: bridge
    name: ${PROJECT_NAME}_main_network
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_IP}/${SUBNET_MASK}